default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: nikita
  password: nikita
  timeout: 5000

development:
  <<: *default
  database: training_dev

test:
  <<: *default
  database: training_test

production:
  <<: *default
  database: training_prod
